<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
use App\{Auth,Csrf,Database,Env,View};
Env::load(dirname(__DIR__).'/.env');
$sessionMinutes=24;
try{$value=Database::connection()->query("SELECT value FROM settings WHERE key='session_timeout_minutes'")->fetchColumn();if($value!==false)$sessionMinutes=max(0,(int)$value);}catch(Throwable){}
$sessionSeconds=$sessionMinutes===0?315360000:$sessionMinutes*60;
ini_set('session.gc_maxlifetime',(string)$sessionSeconds);
session_name('bitchin_kitchen'); session_start(['cookie_lifetime'=>$sessionMinutes===0?$sessionSeconds:0,'cookie_httponly'=>true,'cookie_samesite'=>'Lax','cookie_secure'=>isset($_SERVER['HTTPS'])]);
if(!empty($_SESSION['user_id'])&&$sessionMinutes>0&&!empty($_SESSION['_last_activity'])&&time()-$_SESSION['_last_activity']>$sessionSeconds){unset($_SESSION['user_id']);session_regenerate_id(true);$_SESSION['_flash'][]=['error','Your session expired due to inactivity. Please sign in again.'];}
if(!empty($_SESSION['user_id']))$_SESSION['_last_activity']=time();

function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function url(string $path=''): string { return rtrim((string)App\Env::get('APP_URL',''),'/').$path; }
function redirect(string $to): never { header('Location: '.$to); exit; }
function abort(int $code, string $message=''): never { http_response_code($code); App\View::render('error',['code'=>$code,'message'=>$message ?: ($code===403?'That is not yours to edit.':'Page not found.')]); exit; }
function flash(string $message, string $type='success'): void { $_SESSION['_flash'][]=[$type,$message]; }
function csrf(): string { return '<input type="hidden" name="_token" value="'.e(App\Csrf::token()).'">'; }
function method_is(string $method): bool { return $_SERVER['REQUEST_METHOD'] === $method; }
function recipe(int $id, bool $includePrivate=false): array {
    $sql='SELECT r.*,u.name owner_name,c.name cuisine_name,(SELECT filename FROM recipe_photos WHERE recipe_id=r.id ORDER BY sort_order,id LIMIT 1) thumbnail FROM recipes r JOIN users u ON u.id=r.user_id LEFT JOIN cuisines c ON c.id=r.cuisine_id WHERE r.id=?';
    if(!$includePrivate) $sql.=' AND r.is_public=true'; $q=Database::connection()->prepare($sql); $q->execute([$id]); return $q->fetch() ?: abort(404);
}
function save_photos(int $recipeId): void {
    if(empty($_FILES['photos']['name'][0])) return;
    $max=(int)Env::get('UPLOAD_MAX_FILE_MB',8)*1024*1024; $finfo=new finfo(FILEINFO_MIME_TYPE); $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];
    $order=(int)Database::connection()->query('SELECT COALESCE(MAX(sort_order),-1)+1 FROM recipe_photos WHERE recipe_id='.(int)$recipeId)->fetchColumn();
    foreach($_FILES['photos']['tmp_name'] as $i=>$tmp){ if($_FILES['photos']['error'][$i]!==UPLOAD_ERR_OK) continue; if($_FILES['photos']['size'][$i]>$max) continue; $mime=$finfo->file($tmp); if(!isset($allowed[$mime])) continue; $name=bin2hex(random_bytes(16)).'.'.$allowed[$mime]; if(move_uploaded_file($tmp,__DIR__.'/uploads/'.$name)){ $q=Database::connection()->prepare('INSERT INTO recipe_photos(recipe_id,filename,sort_order) VALUES(?,?,?)'); $q->execute([$recipeId,$name,$order++]); } }
}
function taxonomy_options(int $recipeId=0): array {
    $selected=[];if($recipeId){$q=Database::connection()->prepare('SELECT tag_id FROM recipe_tags WHERE recipe_id=?');$q->execute([$recipeId]);$selected=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));}
    return ['cuisines'=>Database::connection()->query('SELECT * FROM cuisines ORDER BY name')->fetchAll(),'tags'=>Database::connection()->query('SELECT * FROM tags ORDER BY name')->fetchAll(),'selectedTags'=>$selected];
}
function sync_recipe_tags(int $recipeId, array $tagIds, array $previous=[]): void {
    $tagIds=array_unique(array_filter(array_map('intval',$tagIds),fn($id)=>$id>0));$pdo=Database::connection();$q=$pdo->prepare('DELETE FROM recipe_tags WHERE recipe_id=?');$q->execute([$recipeId]);
    $check=$pdo->prepare('SELECT is_active FROM tags WHERE id=?');$insert=$pdo->prepare('INSERT INTO recipe_tags(recipe_id,tag_id) VALUES(?,?) ON CONFLICT DO NOTHING');
    foreach($tagIds as $tagId){$check->execute([$tagId]);$active=$check->fetchColumn();if($active===true||$active==='t'||$active===1||$active==='1'||in_array($tagId,$previous,true))$insert->execute([$recipeId,$tagId]);}
}

$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH) ?: '/';
try {
try {
    $installed=Database::connection()->query("SELECT value FROM settings WHERE key='installed_at'")->fetchColumn();
    if(!$installed) abort(503,'The application has not been provisioned. Run setup.sh as root.');
} catch(Throwable) { abort(503,'The application has not been provisioned. Run setup.sh as root.'); }

if(method_is('POST')&&preg_match('#^/recipes/(\d+)$#',$path,$taxonomyMatch)){$taxonomyUser=Auth::requireUser();Csrf::verify();$taxonomyRecipe=recipe((int)$taxonomyMatch[1],true);if((int)$taxonomyUser['id']!==(int)$taxonomyRecipe['user_id'])abort(403);$previous=taxonomy_options((int)$taxonomyRecipe['id'])['selectedTags'];$q=Database::connection()->prepare('UPDATE recipes SET cuisine_id=? WHERE id=?');$q->execute([(int)($_POST['cuisine_id']??0)?:null,$taxonomyRecipe['id']]);sync_recipe_tags((int)$taxonomyRecipe['id'],$_POST['tags']??[],$previous);}

if($path==='/' && method_is('GET')) {
    $q=trim($_GET['q']??''); $mine=($_GET['mine']??'')==='1'; $user=Auth::user(); $all=isset($_GET['all'])&&in_array($user['role']??'', ['admin','superadmin'],true);$cuisineId=(int)($_GET['cuisine']??0);$filterTags=array_values(array_unique(array_filter(array_map('intval',$_GET['tags']??[]))));
    if(!$user) { View::render('auth/login'); return; }
    $where=$all?'true':($mine?'r.user_id=:uid':'r.is_public=true'); $params=$mine&&!$all?['uid'=>$user['id']]:[];
    if($q!==''){ $where.=" AND r.search_vector @@ websearch_to_tsquery('english',:q)"; $params['q']=$q; }
    if($cuisineId){$where.=' AND r.cuisine_id=:cuisine';$params['cuisine']=$cuisineId;}if($filterTags){$holders=[];foreach($filterTags as $i=>$tagId){$key='tag'.$i;$holders[]=':'.$key;$params[$key]=$tagId;}$where.=' AND r.id IN (SELECT recipe_id FROM recipe_tags WHERE tag_id IN ('.implode(',',$holders).') GROUP BY recipe_id HAVING count(DISTINCT tag_id)='.count($filterTags).')';}
    $sql="SELECT r.*,u.name owner_name,c.name cuisine_name,p.filename thumbnail,(SELECT string_agg(t.name,', ' ORDER BY t.name) FROM recipe_tags rt JOIN tags t ON t.id=rt.tag_id WHERE rt.recipe_id=r.id) tag_names FROM recipes r JOIN users u ON u.id=r.user_id LEFT JOIN cuisines c ON c.id=r.cuisine_id LEFT JOIN LATERAL (SELECT filename FROM recipe_photos WHERE recipe_id=r.id ORDER BY sort_order,id LIMIT 1)p ON true WHERE $where ORDER BY ".($q!==''?"ts_rank(r.search_vector,websearch_to_tsquery('english',:q)) DESC,":"").' r.updated_at DESC LIMIT 60';
    $st=Database::connection()->prepare($sql); $st->execute($params);$cuisines=Database::connection()->query('SELECT * FROM cuisines WHERE is_active=true ORDER BY name')->fetchAll();$tags=Database::connection()->query('SELECT * FROM tags WHERE is_active=true ORDER BY name')->fetchAll(); View::render('home',['recipes'=>$st->fetchAll(),'query'=>$q,'mine'=>$mine,'all'=>$all,'cuisines'=>$cuisines,'tags'=>$tags,'cuisineId'=>$cuisineId,'filterTags'=>$filterTags]);
} elseif($path==='/login' && method_is('GET')) View::render('auth/login');
elseif($path==='/login' && method_is('POST')) { Csrf::verify(); if(Auth::login(trim($_POST['name']??''),$_POST['password']??''))redirect('/');flash('Username or password was incorrect.','error');redirect('/login'); }
elseif($path==='/logout' && method_is('POST')) { Csrf::verify(); session_destroy();redirect('/'); }
elseif($path==='/recipes/new' && method_is('GET')) { Auth::requireUser();$forkId=(int)($_GET['fork']??0);$photos=[];if($forkId){$source=recipe($forkId);$draft=['title'=>$source['title'].' — my version','summary'=>$source['summary'],'ingredients'=>$source['ingredients'],'instructions'=>$source['instructions'],'notes'=>$source['notes'],'is_public'=>true,'forked_from_id'=>$source['id'],'cuisine_id'=>$source['cuisine_id']];$q=Database::connection()->prepare('SELECT * FROM recipe_photos WHERE recipe_id=? ORDER BY sort_order,id');$q->execute([$forkId]);$photos=$q->fetchAll();$tax=taxonomy_options($forkId);}else{$draft=['title'=>'','summary'=>'','ingredients'=>'','instructions'=>'','notes'=>'','is_public'=>true,'forked_from_id'=>null,'cuisine_id'=>null];$tax=taxonomy_options();}View::render('recipes/form',array_merge(['recipe'=>$draft,'photos'=>$photos,'action'=>'/recipes'],$tax)); }
elseif($path==='/recipes' && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$title=trim($_POST['title']??'');$ingredients=trim($_POST['ingredients']??'');$instructions=trim($_POST['instructions']??'');$sourceId=(int)($_POST['forked_from_id']??0);if($sourceId)recipe($sourceId);if($title===''||$ingredients===''||$instructions===''){flash('Title, ingredients, and instructions are required.','error');redirect('/recipes/new'.($sourceId?'?fork='.$sourceId:''));}$q=Database::connection()->prepare('INSERT INTO recipes(user_id,forked_from_id,cuisine_id,title,summary,ingredients,instructions,notes,is_public)VALUES(?,?,?,?,?,?,?,?,?) RETURNING id');$q->execute([$u['id'],$sourceId?:null,(int)($_POST['cuisine_id']??0)?:null,$title,trim($_POST['summary']??''),$ingredients,$instructions,trim($_POST['notes']??''),isset($_POST['is_public'])]);$id=(int)$q->fetchColumn();sync_recipe_tags($id,$_POST['tags']??[]);if($sourceId){$q=Database::connection()->prepare('INSERT INTO recipe_photos(recipe_id,filename,sort_order) SELECT ?,filename,sort_order FROM recipe_photos WHERE recipe_id=?');$q->execute([$id,$sourceId]);}save_photos($id);flash('Recipe is fresh from the oven!');redirect('/recipes/'.$id); }
elseif(preg_match('#^/recipes/(\d+)$#',$path,$m) && method_is('GET')) { $u=Auth::user();$r=recipe((int)$m[1],true);$admin=$u&&in_array($u['role'],['admin','superadmin'],true);if(!$r['is_public']&&(!$u||(int)$u['id']!==(int)$r['user_id'])&&!$admin)abort(404);$q=Database::connection()->prepare('SELECT * FROM recipe_photos WHERE recipe_id=? ORDER BY sort_order,id');$q->execute([$r['id']]);$photos=$q->fetchAll();$q=Database::connection()->prepare('SELECT t.* FROM recipe_tags rt JOIN tags t ON t.id=rt.tag_id WHERE rt.recipe_id=? ORDER BY t.name');$q->execute([$r['id']]);View::render('recipes/show',['recipe'=>$r,'photos'=>$photos,'recipeTags'=>$q->fetchAll()]); }
elseif(preg_match('#^/recipes/(\d+)/edit$#',$path,$m) && method_is('GET')) { $u=Auth::requireUser();$r=recipe((int)$m[1],true);if((int)$u['id']!==(int)$r['user_id'])abort(403);$q=Database::connection()->prepare('SELECT * FROM recipe_photos WHERE recipe_id=? ORDER BY sort_order,id');$q->execute([$r['id']]);View::render('recipes/form',array_merge(['recipe'=>$r,'photos'=>$q->fetchAll(),'action'=>'/recipes/'.$r['id']],taxonomy_options((int)$r['id']))); }
elseif(preg_match('#^/recipes/(\d+)$#',$path,$m) && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1],true);if((int)$u['id']!==(int)$r['user_id'])abort(403);$q=Database::connection()->prepare('UPDATE recipes SET title=?,summary=?,ingredients=?,instructions=?,notes=?,is_public=?,updated_at=NOW() WHERE id=?');$q->execute([trim($_POST['title']??''),trim($_POST['summary']??''),trim($_POST['ingredients']??''),trim($_POST['instructions']??''),trim($_POST['notes']??''),isset($_POST['is_public']),$r['id']]);$remove=array_unique(array_map('intval',$_POST['remove_photos']??[]));foreach($remove as $photoId){$q=Database::connection()->prepare('DELETE FROM recipe_photos WHERE id=? AND recipe_id=? RETURNING filename');$q->execute([$photoId,$r['id']]);$filename=$q->fetchColumn();if($filename){$check=Database::connection()->prepare('SELECT count(*) FROM recipe_photos WHERE filename=?');$check->execute([$filename]);if((int)$check->fetchColumn()===0){$file=__DIR__.'/uploads/'.basename($filename);if(is_file($file))unlink($file);}}}$primary=(int)($_POST['primary_photo']??0);if($primary&&!in_array($primary,$remove,true)){$q=Database::connection()->prepare('SELECT count(*) FROM recipe_photos WHERE id=? AND recipe_id=?');$q->execute([$primary,$r['id']]);if((int)$q->fetchColumn()===1){$q=Database::connection()->prepare('UPDATE recipe_photos SET sort_order=sort_order+1 WHERE recipe_id=?');$q->execute([$r['id']]);$q=Database::connection()->prepare('UPDATE recipe_photos SET sort_order=0 WHERE id=? AND recipe_id=?');$q->execute([$primary,$r['id']]);}}save_photos((int)$r['id']);flash('Recipe updated.');redirect('/recipes/'.$r['id']); }
elseif(preg_match('#^/recipes/(\d+)/fork$#',$path,$m) && method_is('POST')) { Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1]);redirect('/recipes/new?fork='.$r['id']); }
elseif(preg_match('#^/recipes/(\d+)/delete$#',$path,$m) && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1],true);$canDelete=(int)$u['id']===(int)$r['user_id']||in_array($u['role'],['admin','superadmin'],true);if(!$canDelete)abort(403);$q=Database::connection()->prepare('SELECT filename FROM recipe_photos WHERE recipe_id=?');$q->execute([$r['id']]);$filenames=$q->fetchAll(PDO::FETCH_COLUMN);$q=Database::connection()->prepare('DELETE FROM recipes WHERE id=?');$q->execute([$r['id']]);foreach($filenames as $filename){$q=Database::connection()->prepare('SELECT count(*) FROM recipe_photos WHERE filename=?');$q->execute([$filename]);if((int)$q->fetchColumn()===0){$file=__DIR__.'/uploads/'.basename($filename);if(is_file($file))unlink($file);}}flash('Recipe deleted.');redirect('/'); }
elseif($path==='/admin/users' && method_is('GET')) { $u=Auth::requireAdmin();$users=Database::connection()->query('SELECT id,name,role,created_at FROM users ORDER BY created_at')->fetchAll();View::render('admin/users',['users'=>$users,'current'=>$u]); }
elseif($path==='/admin/users' && method_is('POST')) { Auth::requireAdmin();Csrf::verify();$name=trim($_POST['name']??'');$password=$_POST['password']??'';$role=$_POST['role']??'user';if(strlen($name)<2||strlen($name)>100||strlen($password)<8||!in_array($role,['user','admin'],true)){flash('Use a unique username, a password of at least 8 characters, and a valid role.','error');redirect('/admin/users');}try{$q=Database::connection()->prepare('INSERT INTO users(name,password_hash,role) VALUES(?,?,?)');$q->execute([$name,password_hash($password,PASSWORD_DEFAULT),$role]);flash('User created.');}catch(PDOException){flash('That username is already in use.','error');}redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/role$#',$path,$m)&&method_is('POST')) { $u=Auth::requireAdmin();Csrf::verify();$role=$_POST['role']??'user';if(!in_array($role,['admin','user'],true))abort(422);$target=(int)$m[1];if($target===(int)$u['id'])abort(422,'You cannot change your own role.');$q=Database::connection()->prepare("UPDATE users SET role=? WHERE id=? AND role<>'superadmin'");$q->execute([$role,$target]);flash('User role updated.');redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/password$#',$path,$m)&&method_is('POST')) { $u=Auth::requireAdmin();Csrf::verify();$password=$_POST['password']??'';if(strlen($password)<8){flash('Passwords must contain at least 8 characters.','error');redirect('/admin/users');}$target=(int)$m[1];$q=Database::connection()->prepare('SELECT role FROM users WHERE id=?');$q->execute([$target]);$targetRole=$q->fetchColumn();if(!$targetRole)abort(404);if($targetRole==='superadmin'&&($u['role']!=='superadmin'||$target!==(int)$u['id']))abort(403,'The superadmin password cannot be changed by another account.');$q=Database::connection()->prepare('UPDATE users SET password_hash=? WHERE id=?');$q->execute([password_hash($password,PASSWORD_DEFAULT),$target]);flash('Password updated.');redirect('/admin/users'); }
elseif($path==='/admin/taxonomy'&&method_is('GET')) { Auth::requireAdmin();View::render('admin/taxonomy',['cuisines'=>Database::connection()->query('SELECT * FROM cuisines ORDER BY name')->fetchAll(),'tags'=>Database::connection()->query('SELECT * FROM tags ORDER BY name')->fetchAll()]); }
elseif($path==='/admin/taxonomy'&&method_is('POST')) { Auth::requireAdmin();Csrf::verify();$type=$_POST['type']??'';$table=$type==='cuisine'?'cuisines':($type==='tag'?'tags':null);$name=trim($_POST['name']??'');if(!$table||strlen($name)<2||strlen($name)>80){flash('Enter a valid name of 2–80 characters.','error');redirect('/admin/taxonomy');}try{$q=Database::connection()->prepare("INSERT INTO $table(name) VALUES(?)");$q->execute([$name]);flash(ucfirst($type).' added.');}catch(PDOException){flash('That name already exists.','error');}redirect('/admin/taxonomy'); }
elseif(preg_match('#^/admin/taxonomy/(cuisine|tag)/(\d+)$#',$path,$m)&&method_is('POST')) { Auth::requireAdmin();Csrf::verify();$table=$m[1]==='cuisine'?'cuisines':'tags';$name=trim($_POST['name']??'');if(strlen($name)<2||strlen($name)>80){flash('Enter a valid name of 2–80 characters.','error');redirect('/admin/taxonomy');}$q=Database::connection()->prepare("UPDATE $table SET name=?,is_active=? WHERE id=?");$q->execute([$name,isset($_POST['is_active']),(int)$m[2]]);flash(ucfirst($m[1]).' updated.');redirect('/admin/taxonomy'); }
elseif($path==='/admin/settings'&&method_is('GET')) { Auth::requireSuperadmin();$value=Database::connection()->query("SELECT value FROM settings WHERE key='session_timeout_minutes'")->fetchColumn();View::render('admin/settings',['sessionMinutes'=>$value===false?24:(int)$value]); }
elseif($path==='/admin/settings'&&method_is('POST')) { Auth::requireSuperadmin();Csrf::verify();$minutes=filter_var($_POST['session_timeout_minutes']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>5256000]]);if($minutes===false){flash('Enter a whole number from 0 to 5,256,000.','error');redirect('/admin/settings');}$q=Database::connection()->prepare("INSERT INTO settings(key,value)VALUES('session_timeout_minutes',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value");$q->execute([(string)$minutes]);flash($minutes===0?'Sessions will no longer expire due to inactivity.':'Session timeout updated.');redirect('/admin/settings'); }
else abort(404);
} catch(PDOException $e){ if(Env::bool('APP_DEBUG')) throw $e; abort(500,'Something went wrong in the kitchen.'); }
