<?php
declare(strict_types=1);
require dirname(__DIR__).'/vendor/autoload.php';
use App\{Auth,Csrf,Database,Env,LoginRateLimiter,PasswordPolicy,RecipeImporter,View};
Env::load(dirname(__DIR__).'/.env');
$sessionMinutes=24;
try{$value=Database::connection()->query("SELECT value FROM settings WHERE key='session_timeout_minutes'")->fetchColumn();if($value!==false)$sessionMinutes=max(0,(int)$value);}catch(Throwable){}
$sessionSeconds=$sessionMinutes===0?315360000:$sessionMinutes*60;
ini_set('session.gc_maxlifetime',(string)$sessionSeconds);
session_name('bitchin_kitchen'); session_start(['cookie_lifetime'=>$sessionMinutes===0?$sessionSeconds:0,'cookie_httponly'=>true,'cookie_samesite'=>'Lax','cookie_secure'=>isset($_SERVER['HTTPS'])]);
if(!empty($_SESSION['user_id'])&&$sessionMinutes>0&&!empty($_SESSION['_last_activity'])&&time()-$_SESSION['_last_activity']>$sessionSeconds){unset($_SESSION['user_id']);session_regenerate_id(true);$_SESSION['_flash'][]=['error','Your session expired due to inactivity. Please sign in again.'];}
if(!empty($_SESSION['user_id']))$_SESSION['_last_activity']=time();

function e(mixed $v): string { return htmlspecialchars((string)$v, ENT_QUOTES, 'UTF-8'); }
function url(string $path=''): string { return rtrim((string)App\Env::get('APP_URL',''),'/').$path; }
function redirect(string $to): never { header('Location: '.$to); exit; }
function abort(int $code, string $message=''): never { http_response_code($code); App\View::render('error',['code'=>$code,'message'=>$message ?: ($code===403?'That is not yours to edit.':'Page not found.')]); exit; }
function flash(string $message, string $type='success'): void { $_SESSION['_flash'][]=[$type,$message]; }
function csrf(): string { return '<input type="hidden" name="_token" value="'.e(App\Csrf::token()).'">'; }
function method_is(string $method): bool { return $_SERVER['REQUEST_METHOD'] === $method; }
function ip_in_cidr(string $ip, string $cidr): bool {
    [$network,$bits]=array_pad(explode('/',trim($cidr),2),2,null);$address=@inet_pton($ip);$base=@inet_pton($network);if($address===false||$base===false||strlen($address)!==strlen($base)||($bits!==null&&!ctype_digit($bits)))return false;$maxBits=strlen($address)*8;$bits=$bits===null?$maxBits:(int)$bits;if($bits<0||$bits>$maxBits)return false;$bytes=intdiv($bits,8);$remainder=$bits%8;if($bytes&&substr($address,0,$bytes)!==substr($base,0,$bytes))return false;if(!$remainder)return true;$mask=(0xff<<(8-$remainder))&0xff;return (ord($address[$bytes])&$mask)===(ord($base[$bytes])&$mask);
}
function client_ip(): string {
    $remote=filter_var($_SERVER['REMOTE_ADDR']??'',FILTER_VALIDATE_IP)?:'0.0.0.0';$trusted=array_values(array_filter(array_map('trim',explode(',',(string)Env::get('TRUSTED_PROXY_CIDRS','')))));$isTrusted=function(string $ip)use($trusted):bool{foreach($trusted as $cidr)if(ip_in_cidr($ip,$cidr))return true;return false;};if(!$trusted||!$isTrusted($remote))return $remote;$forwarded=array_values(array_filter(array_map('trim',explode(',',$_SERVER['HTTP_X_FORWARDED_FOR']??'')),fn($ip)=>filter_var($ip,FILTER_VALIDATE_IP)!==false));$current=$remote;for($i=count($forwarded)-1;$i>=0&&$isTrusted($current);$i--)$current=$forwarded[$i];return $current;
}
function recipe(int $id, bool $includePrivate=false): array {
    $sql='SELECT r.*,u.name owner_name,c.name cuisine_name,(SELECT filename FROM recipe_photos WHERE recipe_id=r.id ORDER BY sort_order,id LIMIT 1) thumbnail FROM recipes r JOIN users u ON u.id=r.user_id LEFT JOIN cuisines c ON c.id=r.cuisine_id WHERE r.id=?';
    if(!$includePrivate) $sql.=' AND r.is_public=true'; $q=Database::connection()->prepare($sql); $q->execute([$id]); return $q->fetch() ?: abort(404);
}
function store_uploaded_image(string $tmp, string $mime, int $maxDimension=1000): ?string {
    $formats=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];
    if(!isset($formats[$mime])||!function_exists('imagecreatefromstring')) return null;
    $size=@getimagesize($tmp);if(!$size||$size[0]<1||$size[1]<1||$size[0]*$size[1]>40000000)return null;
    $source=@imagecreatefromstring((string)file_get_contents($tmp));if(!$source)return null;
    $scale=min(1,$maxDimension/max($size[0],$size[1]));$width=max(1,(int)round($size[0]*$scale));$height=max(1,(int)round($size[1]*$scale));
    $output=imagecreatetruecolor($width,$height);if(!$output){imagedestroy($source);return null;}
    if($mime!=='image/jpeg'){imagealphablending($output,false);imagesavealpha($output,true);$transparent=imagecolorallocatealpha($output,0,0,0,127);imagefill($output,0,0,$transparent);}
    imagecopyresampled($output,$source,0,0,0,0,$width,$height,$size[0],$size[1]);
    $name=bin2hex(random_bytes(16)).'.'.$formats[$mime];$path=__DIR__.'/uploads/'.$name;
    $saved=match($mime){'image/jpeg'=>function_exists('imagejpeg')&&imagejpeg($output,$path,82),'image/png'=>function_exists('imagepng')&&imagepng($output,$path,6),'image/webp'=>function_exists('imagewebp')&&imagewebp($output,$path,82),'image/gif'=>function_exists('imagegif')&&imagegif($output,$path)};
    imagedestroy($output);imagedestroy($source);if(!$saved){@unlink($path);return null;}return $name;
}
function save_photos(int $recipeId): void {
    if(empty($_FILES['photos']['name'][0])) return;
    $max=(int)Env::get('UPLOAD_MAX_FILE_MB',8)*1024*1024; $finfo=new finfo(FILEINFO_MIME_TYPE); $allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp','image/gif'=>'gif'];
    $order=(int)Database::connection()->query('SELECT COALESCE(MAX(sort_order),-1)+1 FROM recipe_photos WHERE recipe_id='.(int)$recipeId)->fetchColumn();
    foreach($_FILES['photos']['tmp_name'] as $i=>$tmp){ if($_FILES['photos']['error'][$i]!==UPLOAD_ERR_OK) continue; if($_FILES['photos']['size'][$i]>$max) continue; $mime=$finfo->file($tmp); if(!isset($allowed[$mime])) continue; $name=store_uploaded_image($tmp,$mime); if($name){ $q=Database::connection()->prepare('INSERT INTO recipe_photos(recipe_id,filename,sort_order) VALUES(?,?,?)'); $q->execute([$recipeId,$name,$order++]); } }
}
function safe_return_path(string $path, string $fallback='/'): string { return str_starts_with($path,'/')&&!str_starts_with($path,'//')&&parse_url($path,PHP_URL_HOST)===null?$path:$fallback; }
function taxonomy_options(int $recipeId=0): array {
    $selected=[];if($recipeId){$q=Database::connection()->prepare('SELECT tag_id FROM recipe_tags WHERE recipe_id=?');$q->execute([$recipeId]);$selected=array_map('intval',$q->fetchAll(PDO::FETCH_COLUMN));}
    return ['cuisines'=>Database::connection()->query('SELECT * FROM cuisines ORDER BY name')->fetchAll(),'tags'=>Database::connection()->query('SELECT * FROM tags ORDER BY name')->fetchAll(),'selectedTags'=>$selected];
}
function sync_recipe_tags(int $recipeId, array $tagIds, array $previous=[]): void {
    $tagIds=array_unique(array_filter(array_map('intval',$tagIds),fn($id)=>$id>0));$pdo=Database::connection();$source=$pdo->prepare('UPDATE recipes SET source_url=?,source_name=?,source_author=? WHERE id=?');$source->execute([trim($_POST['source_url']??'')?:null,trim($_POST['source_name']??'')?:null,trim($_POST['source_author']??'')?:null,$recipeId]);$q=$pdo->prepare('DELETE FROM recipe_tags WHERE recipe_id=?');$q->execute([$recipeId]);
    $check=$pdo->prepare('SELECT is_active FROM tags WHERE id=?');$insert=$pdo->prepare('INSERT INTO recipe_tags(recipe_id,tag_id) VALUES(?,?) ON CONFLICT DO NOTHING');
    foreach($tagIds as $tagId){$check->execute([$tagId]);$active=$check->fetchColumn();if($active===true||$active==='t'||$active===1||$active==='1'||in_array($tagId,$previous,true))$insert->execute([$recipeId,$tagId]);}
}

$path=parse_url($_SERVER['REQUEST_URI'],PHP_URL_PATH) ?: '/';
try {
try {
    $installed=Database::connection()->query("SELECT value FROM settings WHERE key='installed_at'")->fetchColumn();
    if(!$installed) abort(503,'The application has not been provisioned. Run setup.sh as root.');
} catch(Throwable) { abort(503,'The application has not been provisioned. Run setup.sh as root.'); }

$sessionUser=Auth::user();
if($sessionUser&&$sessionUser['role']!=='superadmin'&&$sessionUser['must_change_password']&&!in_array($path,['/account/password','/logout'],true)){
    redirect('/account/password');
}

if(method_is('POST')&&preg_match('#^/recipes/(\d+)$#',$path,$taxonomyMatch)){$taxonomyUser=Auth::requireUser();Csrf::verify();$taxonomyRecipe=recipe((int)$taxonomyMatch[1],true);if((int)$taxonomyUser['id']!==(int)$taxonomyRecipe['user_id'])abort(403);$previous=taxonomy_options((int)$taxonomyRecipe['id'])['selectedTags'];$q=Database::connection()->prepare('UPDATE recipes SET cuisine_id=?,source_url=?,source_name=?,source_author=? WHERE id=?');$q->execute([(int)($_POST['cuisine_id']??0)?:null,trim($_POST['source_url']??'')?:null,trim($_POST['source_name']??'')?:null,trim($_POST['source_author']??'')?:null,$taxonomyRecipe['id']]);sync_recipe_tags((int)$taxonomyRecipe['id'],$_POST['tags']??[],$previous);}

if(($path==='/'||$path==='/favorites') && method_is('GET')) {
    $q=trim($_GET['q']??''); $mine=($_GET['mine']??'')==='1'; $favorites=$path==='/favorites';$user=Auth::user(); $all=isset($_GET['all'])&&in_array($user['role']??'', ['admin','superadmin'],true);$cuisineId=(int)($_GET['cuisine']??0);$filterTags=array_values(array_unique(array_filter(array_map('intval',$_GET['tags']??[]))));
    if(!$user) { View::render('auth/login'); return; }
    $pageSizes=['9','18','36','60','all'];$pageSize=(string)($_GET['per_page']??$_COOKIE['recipe_page_size']??'9');if(!in_array($pageSize,$pageSizes,true))$pageSize='9';if(isset($_GET['per_page']))setcookie('recipe_page_size',$pageSize,['expires'=>time()+31536000,'path'=>'/','secure'=>isset($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off','httponly'=>true,'samesite'=>'Lax']);$perPage=$pageSize==='all'?null:(int)$pageSize;$page=max(1,(int)($_GET['page']??1));
    $where=$all?'true':($mine?'r.user_id=:uid':'r.is_public=true'); $params=$mine&&!$all?['uid'=>$user['id']]:[];
    if($favorites){$admin=in_array($user['role'],['admin','superadmin'],true);$where='EXISTS(SELECT 1 FROM user_favorites uf WHERE uf.recipe_id=r.id AND uf.user_id=:favorite_uid)'.($admin?'':' AND (r.is_public=true OR r.user_id=:viewer_uid)');$params=['favorite_uid'=>$user['id']];if(!$admin)$params['viewer_uid']=$user['id'];}
    if($q!==''){ $where.=" AND r.search_vector @@ websearch_to_tsquery('english',:q)"; $params['q']=$q; }
    if($cuisineId){$where.=' AND r.cuisine_id=:cuisine';$params['cuisine']=$cuisineId;}if($filterTags){$holders=[];foreach($filterTags as $i=>$tagId){$key='tag'.$i;$holders[]=':'.$key;$params[$key]=$tagId;}$where.=' AND r.id IN (SELECT recipe_id FROM recipe_tags WHERE tag_id IN ('.implode(',',$holders).') GROUP BY recipe_id HAVING count(DISTINCT tag_id)='.count($filterTags).')';}
    $count=Database::connection()->prepare("SELECT count(*) FROM recipes r WHERE $where");$count->execute($params);$total=(int)$count->fetchColumn();$totalPages=$perPage===null?1:max(1,(int)ceil($total/$perPage));$page=min($page,$totalPages);$offset=$perPage===null?0:($page-1)*$perPage;
    $params['favorite_check_uid']=$user['id'];$sql="SELECT r.*,u.name owner_name,c.name cuisine_name,p.filename thumbnail,CASE WHEN EXISTS(SELECT 1 FROM user_favorites fav WHERE fav.recipe_id=r.id AND fav.user_id=:favorite_check_uid) THEN 1 ELSE 0 END is_favorite,(SELECT string_agg(t.name,', ' ORDER BY t.name) FROM recipe_tags rt JOIN tags t ON t.id=rt.tag_id WHERE rt.recipe_id=r.id) tag_names FROM recipes r JOIN users u ON u.id=r.user_id LEFT JOIN cuisines c ON c.id=r.cuisine_id LEFT JOIN LATERAL (SELECT filename FROM recipe_photos WHERE recipe_id=r.id ORDER BY sort_order,id LIMIT 1)p ON true WHERE $where ORDER BY ".($q!==''?"ts_rank(r.search_vector,websearch_to_tsquery('english',:q)) DESC,":"").' r.updated_at DESC'.($perPage===null?'':' LIMIT '.$perPage.' OFFSET '.$offset);
    $st=Database::connection()->prepare($sql); $st->execute($params);$cuisines=Database::connection()->query('SELECT * FROM cuisines WHERE is_active=true ORDER BY name')->fetchAll();$tags=Database::connection()->query('SELECT * FROM tags WHERE is_active=true ORDER BY name')->fetchAll(); View::render('home',['recipes'=>$st->fetchAll(),'query'=>$q,'mine'=>$mine,'all'=>$all,'favorites'=>$favorites,'cuisines'=>$cuisines,'tags'=>$tags,'cuisineId'=>$cuisineId,'filterTags'=>$filterTags,'page'=>$page,'totalPages'=>$totalPages,'total'=>$total,'pageSize'=>$pageSize]);
} elseif($path==='/login' && method_is('GET')) View::render('auth/login');
elseif($path==='/login' && method_is('POST')) { Csrf::verify();$name=trim($_POST['name']??'');$password=$_POST['password']??'';$ip=client_ip();$remaining=LoginRateLimiter::remainingLockout($name,$ip);if($remaining>0){header('Retry-After: '.$remaining);flash('Too many unsuccessful sign-in attempts. Please try again in '.max(1,(int)ceil($remaining/60)).' minute(s).','error');redirect('/login');}if(Auth::login($name,$password)){LoginRateLimiter::clear($name,$ip);redirect('/');}$lockout=LoginRateLimiter::recordFailure($name,$ip);if($lockout>0){header('Retry-After: '.$lockout);flash('Too many unsuccessful sign-in attempts. Please try again in '.max(1,(int)ceil($lockout/60)).' minute(s).','error');}else flash('Username or password was incorrect.','error');redirect('/login'); }
elseif($path==='/logout' && method_is('POST')) { Csrf::verify(); session_destroy();redirect('/'); }
elseif($path==='/account/password'&&method_is('GET')) { $u=Auth::requireUser();View::render('account/password',['passwordPolicy'=>PasswordPolicy::settings(),'mustChange'=>$u['role']!=='superadmin'&&$u['must_change_password'],'passwordExempt'=>$u['role']==='superadmin']); }
elseif($path==='/account/password'&&method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$current=$_POST['current_password']??'';$password=$_POST['password']??'';$confirmation=$_POST['password_confirmation']??'';$q=Database::connection()->prepare('SELECT password_hash FROM users WHERE id=?');$q->execute([$u['id']]);$hash=$q->fetchColumn();if(!$hash||!password_verify($current,$hash)){flash('Your current password was incorrect.','error');redirect('/account/password');}if(password_verify($password,$hash)){flash('Your new password must be different from your current password.','error');redirect('/account/password');}if($password!==$confirmation){flash('The new passwords did not match.','error');redirect('/account/password');}$policy=PasswordPolicy::validate($password,$u['role']);if($policy['errors']){flash(implode(' ',$policy['errors']),'error');redirect('/account/password');}$q=Database::connection()->prepare('UPDATE users SET password_hash=?,must_change_password=false WHERE id=?');$q->execute([password_hash($password,PASSWORD_DEFAULT),$u['id']]);session_regenerate_id(true);flash($policy['breach_unavailable']?'Password changed. Compromised-password screening was temporarily unavailable, so this password could not be checked.':'Password changed.',$policy['breach_unavailable']?'warning':'success');redirect('/'); }
elseif($path==='/recipes/import'&&method_is('POST')) { Auth::requireAdmin();Csrf::verify();header('Content-Type: application/json; charset=utf-8');try{$data=RecipeImporter::import(trim($_POST['url']??''));$q=Database::connection()->prepare('SELECT id FROM cuisines WHERE is_active=true AND lower(name)=lower(?) LIMIT 1');$q->execute([$data['cuisine']]);$data['cuisine_id']=$q->fetchColumn()?:null;$data['tag_ids']=[];$q=Database::connection()->prepare('SELECT id FROM tags WHERE is_active=true AND lower(name)=lower(?) LIMIT 1');foreach($data['keywords'] as $keyword){$q->execute([$keyword]);if($id=$q->fetchColumn())$data['tag_ids'][]=(int)$id;}echo json_encode(['ok'=>true,'recipe'=>$data],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}catch(Throwable $error){http_response_code(422);echo json_encode(['ok'=>false,'error'=>$error->getMessage()]);}exit; }
elseif($path==='/recipes/new' && method_is('GET')) { Auth::requireUser();$forkId=(int)($_GET['fork']??0);$photos=[];if($forkId){$source=recipe($forkId);$draft=['title'=>$source['title'].' — my version','summary'=>$source['summary'],'ingredients'=>$source['ingredients'],'instructions'=>$source['instructions'],'notes'=>$source['notes'],'is_public'=>true,'forked_from_id'=>$source['id'],'cuisine_id'=>$source['cuisine_id']];$q=Database::connection()->prepare('SELECT * FROM recipe_photos WHERE recipe_id=? ORDER BY sort_order,id');$q->execute([$forkId]);$photos=$q->fetchAll();$tax=taxonomy_options($forkId);}else{$draft=['title'=>'','summary'=>'','ingredients'=>'','instructions'=>'','notes'=>'','is_public'=>true,'forked_from_id'=>null,'cuisine_id'=>null];$tax=taxonomy_options();}View::render('recipes/form',array_merge(['recipe'=>$draft,'photos'=>$photos,'action'=>'/recipes'],$tax)); }
elseif($path==='/recipes' && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$title=trim($_POST['title']??'');$ingredients=trim($_POST['ingredients']??'');$instructions=trim($_POST['instructions']??'');$sourceId=(int)($_POST['forked_from_id']??0);if($sourceId)recipe($sourceId);if($title===''||$ingredients===''||$instructions===''){flash('Title, ingredients, and instructions are required.','error');redirect('/recipes/new'.($sourceId?'?fork='.$sourceId:''));}$q=Database::connection()->prepare('INSERT INTO recipes(user_id,forked_from_id,cuisine_id,title,summary,ingredients,instructions,notes,is_public)VALUES(?,?,?,?,?,?,?,?,?) RETURNING id');$q->execute([$u['id'],$sourceId?:null,(int)($_POST['cuisine_id']??0)?:null,$title,trim($_POST['summary']??''),$ingredients,$instructions,trim($_POST['notes']??''),isset($_POST['is_public'])?'true':'false']);$id=(int)$q->fetchColumn();sync_recipe_tags($id,$_POST['tags']??[]);if($sourceId){$q=Database::connection()->prepare('INSERT INTO recipe_photos(recipe_id,filename,sort_order) SELECT ?,filename,sort_order FROM recipe_photos WHERE recipe_id=?');$q->execute([$id,$sourceId]);}save_photos($id);flash('Recipe is fresh from the oven!');redirect('/recipes/'.$id); }
elseif(preg_match('#^/recipes/(\d+)$#',$path,$m) && method_is('GET')) { $u=Auth::user();$r=recipe((int)$m[1],true);$admin=$u&&in_array($u['role'],['admin','superadmin'],true);if(!$r['is_public']&&(!$u||(int)$u['id']!==(int)$r['user_id'])&&!$admin)abort(404);$q=Database::connection()->prepare('SELECT * FROM recipe_photos WHERE recipe_id=? ORDER BY sort_order,id');$q->execute([$r['id']]);$photos=$q->fetchAll();$q=Database::connection()->prepare('SELECT t.* FROM recipe_tags rt JOIN tags t ON t.id=rt.tag_id WHERE rt.recipe_id=? ORDER BY t.name');$q->execute([$r['id']]);$recipeTags=$q->fetchAll();$isFavorite=false;if($u){$q=Database::connection()->prepare('SELECT EXISTS(SELECT 1 FROM user_favorites WHERE user_id=? AND recipe_id=?)');$q->execute([$u['id'],$r['id']]);$isFavorite=in_array($q->fetchColumn(),[true,1,'1','t'],true);}$favoritedBy=null;if($u&&(int)$u['id']===(int)$r['user_id']){$q=Database::connection()->prepare('SELECT u.name FROM user_favorites f JOIN users u ON u.id=f.user_id WHERE f.recipe_id=? ORDER BY lower(u.name)');$q->execute([$r['id']]);$favoritedBy=$q->fetchAll(PDO::FETCH_COLUMN);}View::render('recipes/show',['recipe'=>$r,'photos'=>$photos,'recipeTags'=>$recipeTags,'isFavorite'=>$isFavorite,'favoritedBy'=>$favoritedBy]); }
elseif(preg_match('#^/recipes/(\d+)/edit$#',$path,$m) && method_is('GET')) { $u=Auth::requireUser();$r=recipe((int)$m[1],true);if((int)$u['id']!==(int)$r['user_id'])abort(403);$q=Database::connection()->prepare('SELECT * FROM recipe_photos WHERE recipe_id=? ORDER BY sort_order,id');$q->execute([$r['id']]);View::render('recipes/form',array_merge(['recipe'=>$r,'photos'=>$q->fetchAll(),'action'=>'/recipes/'.$r['id']],taxonomy_options((int)$r['id']))); }
elseif(preg_match('#^/recipes/(\d+)$#',$path,$m) && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1],true);if((int)$u['id']!==(int)$r['user_id'])abort(403);$q=Database::connection()->prepare('UPDATE recipes SET title=?,summary=?,ingredients=?,instructions=?,notes=?,is_public=?,updated_at=NOW() WHERE id=?');$q->execute([trim($_POST['title']??''),trim($_POST['summary']??''),trim($_POST['ingredients']??''),trim($_POST['instructions']??''),trim($_POST['notes']??''),isset($_POST['is_public'])?'true':'false',$r['id']]);$remove=array_unique(array_map('intval',$_POST['remove_photos']??[]));foreach($remove as $photoId){$q=Database::connection()->prepare('DELETE FROM recipe_photos WHERE id=? AND recipe_id=? RETURNING filename');$q->execute([$photoId,$r['id']]);$filename=$q->fetchColumn();if($filename){$check=Database::connection()->prepare('SELECT count(*) FROM recipe_photos WHERE filename=?');$check->execute([$filename]);if((int)$check->fetchColumn()===0){$file=__DIR__.'/uploads/'.basename($filename);if(is_file($file))unlink($file);}}}$primary=(int)($_POST['primary_photo']??0);if($primary&&!in_array($primary,$remove,true)){$q=Database::connection()->prepare('SELECT count(*) FROM recipe_photos WHERE id=? AND recipe_id=?');$q->execute([$primary,$r['id']]);if((int)$q->fetchColumn()===1){$q=Database::connection()->prepare('UPDATE recipe_photos SET sort_order=sort_order+1 WHERE recipe_id=?');$q->execute([$r['id']]);$q=Database::connection()->prepare('UPDATE recipe_photos SET sort_order=0 WHERE id=? AND recipe_id=?');$q->execute([$primary,$r['id']]);}}save_photos((int)$r['id']);flash('Recipe updated.');redirect('/recipes/'.$r['id']); }
elseif(preg_match('#^/recipes/(\d+)/fork$#',$path,$m) && method_is('POST')) { Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1]);redirect('/recipes/new?fork='.$r['id']); }
elseif(preg_match('#^/recipes/(\d+)/favorite$#',$path,$m) && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1],true);$admin=in_array($u['role'],['admin','superadmin'],true);if(!$r['is_public']&&(int)$r['user_id']!==(int)$u['id']&&!$admin)abort(404);$q=Database::connection()->prepare('DELETE FROM user_favorites WHERE user_id=? AND recipe_id=? RETURNING recipe_id');$q->execute([$u['id'],$r['id']]);$favorited=false;if(!$q->fetchColumn()){$q=Database::connection()->prepare('INSERT INTO user_favorites(user_id,recipe_id) VALUES(?,?) ON CONFLICT DO NOTHING');$q->execute([$u['id'],$r['id']]);$favorited=true;}if(str_contains($_SERVER['HTTP_ACCEPT']??'','application/json')){header('Content-Type: application/json; charset=utf-8');echo json_encode(['ok'=>true,'favorited'=>$favorited]);exit;}redirect(safe_return_path($_POST['return_to']??'', '/recipes/'.$r['id'])); }
elseif(preg_match('#^/recipes/(\d+)/delete$#',$path,$m) && method_is('POST')) { $u=Auth::requireUser();Csrf::verify();$r=recipe((int)$m[1],true);$canDelete=(int)$u['id']===(int)$r['user_id']||in_array($u['role'],['admin','superadmin'],true);if(!$canDelete)abort(403);$q=Database::connection()->prepare('SELECT filename FROM recipe_photos WHERE recipe_id=?');$q->execute([$r['id']]);$filenames=$q->fetchAll(PDO::FETCH_COLUMN);$q=Database::connection()->prepare('DELETE FROM recipes WHERE id=?');$q->execute([$r['id']]);foreach($filenames as $filename){$q=Database::connection()->prepare('SELECT count(*) FROM recipe_photos WHERE filename=?');$q->execute([$filename]);if((int)$q->fetchColumn()===0){$file=__DIR__.'/uploads/'.basename($filename);if(is_file($file))unlink($file);}}flash('Recipe deleted.');redirect('/'); }
elseif($path==='/calculators'&&method_is('GET')) { Auth::requireUser();View::render('calculators'); }
elseif($path==='/admin/users' && method_is('GET')) { $u=Auth::requireAdmin();$users=Database::connection()->query('SELECT id,name,role,CASE WHEN must_change_password THEN 1 ELSE 0 END must_change_password,created_at FROM users ORDER BY created_at')->fetchAll();View::render('admin/users',['users'=>$users,'current'=>$u,'passwordPolicy'=>PasswordPolicy::settings()]); }
elseif($path==='/admin/users' && method_is('POST')) { Auth::requireAdmin();Csrf::verify();$name=trim($_POST['name']??'');$password=$_POST['password']??'';$role=$_POST['role']??'user';if(strlen($name)<2||strlen($name)>100||!in_array($role,['user','admin'],true)){flash('Use a unique username of 2–100 characters and a valid role.','error');redirect('/admin/users');}$policy=PasswordPolicy::validate($password,$role);if($policy['errors']){flash(implode(' ',$policy['errors']),'error');redirect('/admin/users');}try{$q=Database::connection()->prepare('INSERT INTO users(name,password_hash,role) VALUES(?,?,?)');$q->execute([$name,password_hash($password,PASSWORD_DEFAULT),$role]);flash($policy['breach_unavailable']?'User created. Compromised-password screening was temporarily unavailable, so this password could not be checked.':'User created.',$policy['breach_unavailable']?'warning':'success');}catch(PDOException){flash('That username is already in use.','error');}redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/role$#',$path,$m)&&method_is('POST')) { $u=Auth::requireAdmin();Csrf::verify();$role=$_POST['role']??'user';if(!in_array($role,['admin','user'],true))abort(422);$target=(int)$m[1];if($target===(int)$u['id'])abort(422,'You cannot change your own role.');$q=Database::connection()->prepare("UPDATE users SET role=? WHERE id=? AND role<>'superadmin'");$q->execute([$role,$target]);flash('User role updated.');redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/password$#',$path,$m)&&method_is('POST')) { $u=Auth::requireAdmin();Csrf::verify();$password=$_POST['password']??'';$target=(int)$m[1];$q=Database::connection()->prepare('SELECT role FROM users WHERE id=?');$q->execute([$target]);$targetRole=$q->fetchColumn();if(!$targetRole)abort(404);if($targetRole==='superadmin'&&($u['role']!=='superadmin'||$target!==(int)$u['id']))abort(403,'The superadmin password cannot be changed by another account.');$policy=PasswordPolicy::validate($password,$targetRole);if($policy['errors']){flash(implode(' ',$policy['errors']),'error');redirect('/admin/users');}$q=Database::connection()->prepare('UPDATE users SET password_hash=? WHERE id=?');$q->execute([password_hash($password,PASSWORD_DEFAULT),$target]);flash($policy['breach_unavailable']?'Password updated. Compromised-password screening was temporarily unavailable, so this password could not be checked.':'Password updated.',$policy['breach_unavailable']?'warning':'success');redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/must-change$#',$path,$m)&&method_is('POST')) { Auth::requireAdmin();Csrf::verify();$target=(int)$m[1];$required=isset($_POST['required']);$q=Database::connection()->prepare("UPDATE users SET must_change_password=? WHERE id=? AND role<>'superadmin' RETURNING name");$q->execute([$required?'true':'false',$target]);$name=$q->fetchColumn();if(!$name)abort(404);flash($required?$name.' must choose a new password at their next request.':$name.' is no longer required to change their password.');redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/name$#',$path,$m)&&method_is('POST')) { Auth::requireSuperadmin();Csrf::verify();$target=(int)$m[1];$name=trim($_POST['name']??'');if(strlen($name)<2||strlen($name)>100){flash('Usernames must contain 2–100 characters.','error');redirect('/admin/users');}try{$q=Database::connection()->prepare('UPDATE users SET name=? WHERE id=? RETURNING id');$q->execute([$name,$target]);if(!$q->fetchColumn())abort(404);flash('Username updated.');}catch(PDOException $error){if($error->getCode()==='23505')flash('That username is already in use.','error');else throw $error;}redirect('/admin/users'); }
elseif(preg_match('#^/admin/users/(\d+)/delete$#',$path,$m)&&method_is('POST')) { Auth::requireSuperadmin();Csrf::verify();$target=(int)$m[1];$pdo=Database::connection();$q=$pdo->prepare("SELECT name,role FROM users WHERE id=?");$q->execute([$target]);$targetUser=$q->fetch();if(!$targetUser)abort(404);if($targetUser['role']==='superadmin')abort(403,'The superadmin account cannot be deleted.');$q=$pdo->prepare('SELECT DISTINCT p.filename FROM recipe_photos p JOIN recipes r ON r.id=p.recipe_id WHERE r.user_id=?');$q->execute([$target]);$filenames=$q->fetchAll(PDO::FETCH_COLUMN);$q=$pdo->prepare("DELETE FROM users WHERE id=? AND role<>'superadmin'");$q->execute([$target]);foreach($filenames as $filename){$q=$pdo->prepare('SELECT count(*) FROM recipe_photos WHERE filename=?');$q->execute([$filename]);if((int)$q->fetchColumn()===0){$file=__DIR__.'/uploads/'.basename($filename);if(is_file($file))unlink($file);}}flash($targetUser['name'].' and their recipes were deleted.');redirect('/admin/users'); }
elseif($path==='/admin/taxonomy'&&method_is('GET')) { Auth::requireAdmin();redirect('/admin/settings'); }
elseif($path==='/admin/taxonomy'&&method_is('POST')) { Auth::requireAdmin();Csrf::verify();$type=$_POST['type']??'';$table=$type==='cuisine'?'cuisines':($type==='tag'?'tags':null);$name=trim($_POST['name']??'');if(!$table||strlen($name)<2||strlen($name)>80){flash('Enter a valid name of 2–80 characters.','error');redirect('/admin/settings');}try{$q=Database::connection()->prepare("INSERT INTO $table(name) VALUES(?)");$q->execute([$name]);flash(ucfirst($type).' added.');}catch(PDOException){flash('That name already exists.','error');}redirect('/admin/settings'); }
elseif(preg_match('#^/admin/taxonomy/(cuisine|tag)/(\d+)$#',$path,$m)&&method_is('POST')) { Auth::requireAdmin();Csrf::verify();$table=$m[1]==='cuisine'?'cuisines':'tags';$name=trim($_POST['name']??'');if(strlen($name)<2||strlen($name)>80){flash('Enter a valid name of 2–80 characters.','error');redirect('/admin/settings');}$q=Database::connection()->prepare("UPDATE $table SET name=?,is_active=? WHERE id=?");$q->execute([$name,isset($_POST['is_active'])?'true':'false',(int)$m[2]]);flash(ucfirst($m[1]).' updated.');redirect('/admin/settings'); }
elseif($path==='/admin/settings'&&method_is('GET')) { $settingsUser=Auth::requireAdmin();$value=Database::connection()->query("SELECT value FROM settings WHERE key='session_timeout_minutes'")->fetchColumn();$brandIcon=Database::connection()->query("SELECT value FROM settings WHERE key='brand_icon'")->fetchColumn()?:null;View::render('admin/settings',['sessionMinutes'=>$value===false?24:(int)$value,'brandIcon'=>$brandIcon,'settingsUser'=>$settingsUser,'loginPolicy'=>LoginRateLimiter::settings(),'passwordPolicy'=>PasswordPolicy::settings(),'cuisines'=>Database::connection()->query('SELECT * FROM cuisines ORDER BY name')->fetchAll(),'tags'=>Database::connection()->query('SELECT * FROM tags ORDER BY name')->fetchAll()]); }
elseif($path==='/admin/settings'&&method_is('POST')) { Auth::requireSuperadmin();Csrf::verify();$minutes=filter_var($_POST['session_timeout_minutes']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>0,'max_range'=>5256000]]);if($minutes===false){flash('Enter a whole number from 0 to 5,256,000.','error');redirect('/admin/settings');}$q=Database::connection()->prepare("INSERT INTO settings(key,value)VALUES('session_timeout_minutes',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value");$q->execute([(string)$minutes]);flash($minutes===0?'Sessions will no longer expire due to inactivity.':'Session timeout updated.');redirect('/admin/settings'); }
elseif($path==='/admin/settings/icon'&&method_is('POST')) { Auth::requireSuperadmin();Csrf::verify();$pdo=Database::connection();$current=$pdo->query("SELECT value FROM settings WHERE key='brand_icon'")->fetchColumn()?:null;if(isset($_POST['remove'])){$q=$pdo->prepare("DELETE FROM settings WHERE key='brand_icon'");$q->execute();if($current)@unlink(__DIR__.'/uploads/'.basename($current));flash('The default pie icon is back.');redirect('/admin/settings');}$file=$_FILES['brand_icon']??null;if(!$file||$file['error']!==UPLOAD_ERR_OK||$file['size']>5*1024*1024){flash('Choose an icon no larger than 5 MB.','error');redirect('/admin/settings');}$mime=(new finfo(FILEINFO_MIME_TYPE))->file($file['tmp_name']);$name=is_string($mime)?store_uploaded_image($file['tmp_name'],$mime,512):null;if(!$name){flash('Choose a valid JPEG, PNG, WebP, or GIF image.','error');redirect('/admin/settings');}$q=$pdo->prepare("INSERT INTO settings(key,value)VALUES('brand_icon',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value");$q->execute([$name]);if($current&&$current!==$name)@unlink(__DIR__.'/uploads/'.basename($current));flash('Brand icon updated.');redirect('/admin/settings'); }
elseif($path==='/admin/settings/security'&&method_is('POST')) { Auth::requireSuperadmin();Csrf::verify();$attempts=filter_var($_POST['login_max_attempts']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>100]]);$window=filter_var($_POST['login_window_minutes']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>1440]]);$lockout=filter_var($_POST['login_lockout_minutes']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>1,'max_range'=>1440]]);$length=filter_var($_POST['password_min_length']??null,FILTER_VALIDATE_INT,['options'=>['min_range'=>8,'max_range'=>128]]);$strength=$_POST['password_min_strength']??'';if($attempts===false||$window===false||$lockout===false||$length===false||!in_array($strength,['basic','standard','strong'],true)){flash('Enter valid security settings within the displayed limits.','error');redirect('/admin/settings');}$values=['login_max_attempts'=>(string)$attempts,'login_window_minutes'=>(string)$window,'login_lockout_minutes'=>(string)$lockout,'password_min_length'=>(string)$length,'password_min_strength'=>$strength,'breach_check_enabled'=>isset($_POST['breach_check_enabled'])?'true':'false'];$pdo=Database::connection();$pdo->beginTransaction();try{$q=$pdo->prepare('INSERT INTO settings(key,value)VALUES(?,?) ON CONFLICT(key) DO UPDATE SET value=excluded.value');foreach($values as $key=>$setting)$q->execute([$key,$setting]);$pdo->exec('DELETE FROM login_throttles');$pdo->commit();}catch(Throwable $error){$pdo->rollBack();throw $error;}flash('Security settings updated. Existing temporary lockouts were cleared.');redirect('/admin/settings'); }
else abort(404);
} catch(PDOException $e){ error_log('Bitchin Kitchen database error: '.$e->getMessage());if(Env::bool('APP_DEBUG')) throw $e; abort(500,'Something went wrong in the kitchen.'); }
